### ISSUE TITLE
Footer fix to the bottom.

### ISSUE THREAD

**Issue by thebishaldeb** [NJACKWinterOfCode/Instances#1]
Fix the footer to the bottom and make sure it doesn't overlap with other components

**Comment by shreyateeza** [comment]
I would like to work on this issue. Can you please let me know how to proceed?

**Comment by thebishaldeb** [comment]
Set up the repo in your machine by following the readme. 
Start it and add some data. You can then see that the footer creates problems.
Solve that.

**Comment by thebishaldeb** [comment]
@shreyateeza working on it?

**Comment by dev-sankhadip** [comment]
Is anyone still working on this? I am willing to do it

**Comment by thebishaldeb** [comment]
> Is anyone still working on this? I am willing to do it

Yeas, you may.

**Comment by dev-sankhadip** [comment]
I have opened a pull request, can you please check it out?
