### ISSUE TITLE
Use Bootstrap 4 instead of Bootstrap 3.3.7

### ISSUE THREAD

**Issue by ExpressHermes** [NJACKWinterOfCode/Instances#10]
Currently the project is using bootstrap 3.3.7 which can be updated to Bootstrap 4 for better UI design.

**Comment by vkgupta857** [comment]
I have worked on Bootstrap 4. I can change that. But that needs to be updated in every page. Should I proceed?

**Comment by thebishaldeb** [comment]
> I have worked on Bootstrap 4. I can change that. But that needs to be updated in every page. Should I proceed?

Surely

**Comment by vkgupta857** [comment]
I have made a PR #16 but It is having conflicts. I have updated every page with BS4.

**Comment by devyaniChoubey** [comment]
@thebishaldeb sir I have already added bootstrap 4.1 and registration and login are also based on bootstrap 4.1

**Comment by thebishaldeb** [comment]
@vkgupta857 please resolve those conflicts

**Comment by vkgupta857** [comment]
> @vkgupta857 please resolve those conflicts

OK
