### ISSUE TITLE
alert box appeared when logged in should be improved

### ISSUE THREAD

**Issue by sd8917** [NJACKWinterOfCode/Instances#11]
Instead of permanent alert on the the blog page when logged we use the DISMISING alert.

![Screenshot (62)](https://user-images.githubusercontent.com/34008023/69966266-0a1b3e00-153c-11ea-82bb-e21dcc11dedd.png)

**Comment by thebishaldeb** [comment]
It comes under the #4 issue. You can solve it there only. There's no need of a new issue @sd8917

**Comment by sd8917** [comment]
okk thanks
