### ISSUE TITLE
change the signed in with the icon.

### ISSUE THREAD

**Issue by sd8917** [NJACKWinterOfCode/Instances#12]
when the user is registered the header is showing signed in as username.

![Screenshot (64)](https://user-images.githubusercontent.com/34008023/69972580-df36e700-1547-11ea-9ce7-864306f4561b.png)

**Comment by thebishaldeb** [comment]
What should the change be @sd8917 ?

**Comment by sd8917** [comment]
instead of the **signed in username** we use **icon username**.It contain submenu  for follows:-
1.Total post of the user
2.account setting

**Comment by thebishaldeb** [comment]
Yeah cool.

**Comment by sd8917** [comment]
can i work on it??

**Comment by thebishaldeb** [comment]
Sure go ahead.

**Comment by sd8917** [comment]
review my pr for this issue

**Comment by thebishaldeb** [comment]
@sd8917 you were supposed to make the PR in this repo. Not the main one. Create a PR here.

**Comment by vkgupta857** [comment]
I am unable to find the number of posts by a particular user. Please guide.

**Comment by thebishaldeb** [comment]
You need to render them from the database and show them in an icon.

**Comment by vishal-bhola** [comment]
I'll love to work on this issue.

**Comment by thebishaldeb** [comment]
> I'll love to work on this issue.

Assigning it to you

**Comment by abhisheknaiidu** [comment]
I want to work on this issue, could you assign to me ?

**Comment by thebishaldeb** [comment]
@abhisheknaiidu I csn assign you only after you finish the other ones.
