### ISSUE TITLE
Email ID Validation

### ISSUE THREAD

**Issue by Aastha12345** [NJACKWinterOfCode/Instances#18]
Email Id is not checked for validation.
In register page I typed " hello ''  in mail column and it did not show any message to enter correct mail Id .It can be checked if email user enters is in the valid format or not

**Comment by thebishaldeb** [comment]
Assigning it to you. Check the same for both registration and login page.

**Comment by devyaniChoubey** [comment]
Can i work on this issue.
I have worked with express-validator so I can use it here.

**Comment by anushkamittal** [comment]
can I work on this issue?

**Comment by devyaniChoubey** [comment]
@thebishaldeb I will fix it by today

**Comment by Aastha12345** [comment]
My exams are going on so my schedule is a bit packed.Can I make contributions after 20 December

**Comment by thebishaldeb** [comment]
> My exams are going on so my schedule is a bit packed.Can I make contributions after 20 December

Yeah cool. No problem.

**Comment by thebishaldeb** [comment]
@devyaniChoubey  this one is still assigned to you.

**Comment by anushkamittal** [comment]
Can I work on this @thebishaldeb ?

**Comment by anushkamittal** [comment]
When we click the submit button it is already showing error email not valid.

**Comment by thebishaldeb** [comment]
Okay, I guess I did it then. Closing the issue,
