### ISSUE TITLE
Needs to update the readme

### ISSUE THREAD

**Issue by sgpritam** [NJACKWinterOfCode/Instances#23]
Needs to update the readme.md file properly

**Comment by sgpritam** [comment]
@thebishaldeb I would like to work on this issues

**Comment by thebishaldeb** [comment]
Sure. Upload apt. screenshots and do the needful changes.

**Comment by thebishaldeb** [comment]
Any update?

**Comment by anushkamittal** [comment]
Can I work on this issue?

**Comment by sgpritam** [comment]
I am currently working on it

**Comment by anushkamittal** [comment]
ok

**Comment by thebishaldeb** [comment]
@sgpritam since you're having exam, assigning it to @anushkamittal

**Comment by sgpritam** [comment]
No sir

**Comment by thebishaldeb** [comment]
It is been three days and there is no update. Please look into other issues.

**Comment by sgpritam** [comment]
Ok please update marks

**Comment by sgpritam** [comment]
My score has not yet been updated which I have created a legit issue

**Comment by thebishaldeb** [comment]
Done.

**Comment by anushkamittal** [comment]
Can you please tell me what exact update do you want?

**Comment by thebishaldeb** [comment]
The screenshot of the pages need to be updated, login and register page need to be added.  
make it such that two pages can be shown in own row, with smaller size images. They shoulsd not take up much space.

**Comment by anushkamittal** [comment]
Okay

**Comment by anushkamittal** [comment]
@thebishaldeb I have created a PR. Please review it.
https://github.com/NJACKWinterOfCode/Instances/pull/37
