### ISSUE TITLE
Link broken while editing comment

### ISSUE THREAD

**Issue by vkgupta857** [NJACKWinterOfCode/Instances#24]
While editing a comment, error occurs.

**Comment by thebishaldeb** [comment]
Please put a screenshot of the same in the description.

**Comment by thebishaldeb** [comment]
The blog is not defined is shown as error. 
We need to resolve that.

**Comment by thebishaldeb** [comment]
@devyaniChoubey this is resolved right? I mean there is no error in editing now, right?
