### ISSUE TITLE
Add and edit commit in the same page.

### ISSUE THREAD

**Issue by thebishaldeb** [NJACKWinterOfCode/Instances#30]
The add and edit option should be available in the same page as the blog and need not be redirected to a new pagev for the same.

**Comment by devyaniChoubey** [comment]
Can I work on this issue?

**Comment by thebishaldeb** [comment]
Cool

**Comment by devyaniChoubey** [comment]
@thebishaldeb  it is working fine now. 
I can edit comments also.
It's not showing any error.
