### ISSUE TITLE
Dynamic dates under the blog

### ISSUE THREAD

**Issue by thebishaldeb** [NJACKWinterOfCode/Instances#33]
It shows `10 days ago` under the blog but it should be dynamic.

**Comment by devyaniChoubey** [comment]
Can i work on this issue?

**Comment by devyaniChoubey** [comment]
@thebishaldeb  Please

**Comment by thebishaldeb** [comment]
Email ID validation needs to be done first.

**Comment by anushkamittal** [comment]
can I work on this?

**Comment by devyaniChoubey** [comment]
@thebishaldeb  I will solve both the issues.Please assign this issue to me

**Comment by thebishaldeb** [comment]
One issue per PR actually.

Better you do this, I'll give the prev issue to the other person, since everyone deserves a fair chance.
