### ISSUE TITLE
A profile page for the user

### ISSUE THREAD

**Issue by thebishaldeb** [NJACKWinterOfCode/Instances#35]
There should be a profile page for the user which shows his details and an option to edit the profile while leads him to a prefilled form to edit the profile.

Email, username uniquesness should be chexked.

Password change option should not be there.

The profile page link should end like /username and not with  /id
Link that to the blog page and remove details from there. Only paragraph about the user should be present there and a button to his profile.

**Comment by devyaniChoubey** [comment]
Can I work on this issue?

**Comment by devyaniChoubey** [comment]
@thebishaldeb Please assign this to me

**Comment by vkgupta857** [comment]
I have made a route as /user/:username. @devyaniChoubey you can continue from creating the content of the page. This will save your time.

**Comment by devyaniChoubey** [comment]
@vkgupta857  I have also made that route. As the issue was assigned to me I will work on it.

**Comment by vkgupta857** [comment]
> @vkgupta857 I have also made that route. As the issue was assigned to me I will work on it.

OK :+1:
