### ISSUE TITLE
Like, unlike and dislike option.

### ISSUE THREAD

**Issue by thebishaldeb** [NJACKWinterOfCode/Instances#36]
A user can like and dislike the posts and it should be saved in the database like the comments. A user can like only once and unlike it. Also dislike option should work similarly.

**Comment by anushkamittal** [comment]
can I work on this?

**Comment by thebishaldeb** [comment]
Sure. I also assigned you the README issue. Do that too.

**Comment by anushkamittal** [comment]
okay

**Comment by devyaniChoubey** [comment]
Can I work on this issue?

**Comment by thebishaldeb** [comment]
@anushkamittal is working on it. Please look into other issues.

**Comment by thebishaldeb** [comment]
@anushkamittal  update?

**Comment by anushkamittal** [comment]
I have made the like and dislike button but switching between them is not possible. That once a user has liked a page it cannot dislike it.

**Comment by devyaniChoubey** [comment]
I can do that . I have added that feature in one of my project

**Comment by anushkamittal** [comment]
I have created a PR @thebishaldeb. Please review it.

**Comment by devyaniChoubey** [comment]
@anushkamittal  are you still working on this issue?

**Comment by anushkamittal** [comment]
@devyaniChoubey  yes
