### ISSUE TITLE
Confirm before deletion

### ISSUE THREAD

**Issue by vkgupta857** [NJACKWinterOfCode/Instances#38]
While deleting a post or comment, a confirm notification/pop-up can be asked.

**Comment by thebishaldeb** [comment]
Use bootstap alerts for the same. Make sure to comment on the issue before solving.

**Comment by supershivam13** [comment]
I am working on it

**Comment by abhisheknaiidu** [comment]
@thebishaldeb I have made some changes #45 , could you review and merge.
