### ISSUE TITLE
Footer should be improved.

### ISSUE THREAD

**Issue by abhisheknaiidu** [NJACKWinterOfCode/Instances#41]
Footer must be in bottom of the site.

![instance](https://user-images.githubusercontent.com/55599878/70844526-49b12680-1e68-11ea-8cee-0effa13f67ca.png)

**Comment by abhisheknaiidu** [comment]
@thebishaldeb I have made a PR here https://github.com/NJACKWinterOfCode/Instances/pull/42#issue-353148343 Review and merge it.

**Comment by thebishaldeb** [comment]
Suggested improvements. But from next time, make sure to solve an issue only after I label it.

**Comment by abhisheknaiidu** [comment]
@thebishaldeb ohkk. But could you review my PR #42 and merge it.

**Comment by anushkamittal** [comment]
Can I work on this issue?
