### ISSUE TITLE
Layout update

### ISSUE THREAD

**Issue by vkgupta857** [NJACKWinterOfCode/Instances#48]
Currently, the pages have following problems-
- footer is overlapping with content
- navbar icon is not visible in mobile view
- pictures get scattered in mobile view

The above problems should be removed and the project should be more responsive for all devices.

**Comment by vkgupta857** [comment]
I have done some of them. I will create PR after validation of the issue. More suggestions on this are welcome.

**Comment by thebishaldeb** [comment]
Labelled.

**Comment by vkgupta857** [comment]
Created a PR #60 .
