### ISSUE TITLE
Unable to upload profile picture

### ISSUE THREAD

**Issue by Aastha12345** [NJACKWinterOfCode/Instances#49]
![image](https://user-images.githubusercontent.com/37660499/71303667-e8e29a80-23e1-11ea-94b9-e17eb783f1ba.png)

I am getting this error when i try to register and upload profile picture and hit submit button.

**Comment by Aastha12345** [comment]
@thebishaldeb I would like to give it a try.

**Comment by thebishaldeb** [comment]
Assigned to @Aastha12345
