### ISSUE TITLE
Error uploading instance image

### ISSUE THREAD

**Issue by vkgupta857** [NJACKWinterOfCode/Instances#50]
Following error appears on uploading instance image.

![Screenshot from 2019-12-21 12-07-47](https://user-images.githubusercontent.com/26093574/71304296-cacd6800-23ea-11ea-842c-4b91d86848d8.png)

**Comment by vkgupta857** [comment]
Following error appears on uploading instance image.
![Screenshot from 2019-12-21 12-07-47](https://user-images.githubusercontent.com/26093574/71304296-cacd6800-23ea-11ea-842c-4b91d86848d8.png)

**Comment by Aastha12345** [comment]
@thebishaldeb can i work on it.Its almost the same as the previous one.
