### ISSUE TITLE
A single line to add description

### ISSUE THREAD

**Issue by Aastha12345** [NJACKWinterOfCode/Instances#52]
![image](https://user-images.githubusercontent.com/37660499/71304521-0453a280-23ee-11ea-8ffa-0229664235fc.png)
It is making it difficult to add description. All text is getting stacked in a single line.

**Comment by Aastha12345** [comment]
I have made a pull request #51 for the same. <br>Please review it

**Comment by thebishaldeb** [comment]
This is fixed while solving #8 

I guess it is fine now. We don't need this issue.
