### ISSUE TITLE
no description is shown

### ISSUE THREAD

**Issue by Aastha12345** [NJACKWinterOfCode/Instances#58]
![image](https://user-images.githubusercontent.com/37660499/71355112-095a5280-25a4-11ea-9779-55946687898b.png)

**Comment by Aastha12345** [comment]
i know how to resolve it.can i work on it

**Comment by thebishaldeb** [comment]
Update on this @Aastha12345 ?

**Comment by Aastha12345** [comment]
will do it by tomorrow

**Comment by thebishaldeb** [comment]
Update on this @Aastha12345 ?
