### ISSUE TITLE
edit profile option in Account not working

### ISSUE THREAD

**Issue by Aastha12345** [NJACKWinterOfCode/Instances#59]
after logging when we click account,the profile of user are shown and there is opition to edit it.That option is not working

**Comment by devyaniChoubey** [comment]
@Aastha12345  profile edit option will be shown only if the profile  is of logged in user.And Edit profile is working properly.

**Comment by Aastha12345** [comment]
ok, i tried it ,if cursor is in footer region one is not able to click the button.Else its working fine.
