### ISSUE TITLE
Increase the schema for the user.

### ISSUE THREAD

**Issue by thebishaldeb** [NJACKWinterOfCode/Instances#6]
Increase the schema in models folder.  It should have name, email, phone number, username, password, profile picture and others as required. We need them to build a profile page.

**Comment by Sahastracookcoder1** [comment]
I would like to work on this issue can i?

**Comment by thebishaldeb** [comment]
Cool

**Comment by thebishaldeb** [comment]
Updates?

**Comment by devyaniChoubey** [comment]
I also want to work on this issue

**Comment by thebishaldeb** [comment]
@devyaniChoubey I'll assign you the issue if I don't get any reply from @Sahastracookcoder1 by tomorrow

**Comment by devyaniChoubey** [comment]
okk

**Comment by thebishaldeb** [comment]
Assigning it to @devyaniChoubey
