### ISSUE TITLE
Increase the form in registration page

### ISSUE THREAD

**Issue by thebishaldeb** [NJACKWinterOfCode/Instances#7]
After #6 is done, Increase the form components in the registration page to take in the necessary values.

**Comment by Sahastracookcoder1** [comment]
i would like to work on this issue can i?

**Comment by thebishaldeb** [comment]
Cool

**Comment by thebishaldeb** [comment]
@Sahastracookcoder1 any update?

**Comment by devyaniChoubey** [comment]
@thebishaldeb  Can I work on this issue?

**Comment by thebishaldeb** [comment]
Assigned
