### ISSUE TITLE
Creating Account without an image shows an uncaught error

### ISSUE THREAD

**Issue by Rodriq** [NJACKWinterOfCode/Instances#76]
![image](https://user-images.githubusercontent.com/39289592/71562991-03bfa980-2a89-11ea-8e5a-b9628831e23b.png)

**Comment by thebishaldeb** [comment]
Make it such that a default image is shown in place of that the image if it is not entered during registration

**Comment by Rodriq** [comment]
> Make it such that a default image is shown in place of that the image if it is not entered during registration

Okay. will do.

**Comment by Rodriq** [comment]
@thebishaldeb  I'm concerned about this. I don't think this was handled, yet the issue is closed.
  I have a working progress.

**Comment by thebishaldeb** [comment]
Coding period is over. Thus closed the issue. You can work but wont get any points.
