### ISSUE TITLE
Creating duplicate account logs error but doesn't display to user

### ISSUE THREAD

**Issue by Rodriq** [NJACKWinterOfCode/Instances#77]
Logged Error
![image](https://user-images.githubusercontent.com/39289592/71563062-fb1ba300-2a89-11ea-92ce-22baafa9f860.png)

But page keeps loading with nothing happening.

**Comment by thebishaldeb** [comment]
I need to know the details, where does it occur and stuff like that.

**Comment by Rodriq** [comment]
> I need to know the details, where does it occur and stuff like that.

On the register page.
  I already have an **Admin** user then I tried creating another user with the same username. The front page keeps loading until it fails without any info. Meanwhile, on the console we get the `UserExistsError`.

**Comment by Rodriq** [comment]
@thebishaldeb  Didn't notice any PR that fixed this issue.
  If it'll need some fix, I think I can see into it

**Comment by thebishaldeb** [comment]
Coding period is over.  You can work but wont get any points.
