### ISSUE TITLE
Add markdown

### ISSUE THREAD

**Issue by thebishaldeb** [NJACKWinterOfCode/Instances#8]
Currently no styling can be done in the events text, its just plain paragraph. We need to improve that.

**Comment by shreyateeza** [comment]
@thebishaldeb I would like to work on this issue. Can you please elaborate this?

**Comment by thebishaldeb** [comment]
https://ourcodeworld.com/articles/read/359/top-7-best-markdown-editors-javascript-and-jquery-plugins

follow this link for reference.

The formatted text show appear in the card details.

**Comment by Sahastracookcoder1** [comment]
I would like to work on this issue can i?

**Comment by thebishaldeb** [comment]
Sure.

**Comment by thebishaldeb** [comment]
@Sahastracookcoder1 any update?

**Comment by vkgupta857** [comment]
@thebishaldeb  Please elaborate the issue. I am confused of events. What is this?

**Comment by thebishaldeb** [comment]
By events, I mean the blog post in which markdown needs to be added like it is for Wordpress.

**Comment by vkgupta857** [comment]
I am working on it. Assign me.

**Comment by thebishaldeb** [comment]
@vkgupta857  update?

**Comment by vkgupta857** [comment]
still working on it. Need a little time.

**Comment by thebishaldeb** [comment]
Update?

**Comment by Aastha12345** [comment]
I would also like to work on it
