### ISSUE TITLE
images of blogs not visible in user profile

### ISSUE THREAD

**Issue by Aastha12345** [NJACKWinterOfCode/Instances#83]
when the profile of user is opened,the section in which user's blogs are shown,in them blog images are not visible

**Comment by Aastha12345** [comment]
@thebishaldeb when i pulled changes error is shown when i tried viewing profile of user to view user's blogs.
i recently made a pull requset for the same in which i made use of promises
![image](https://user-images.githubusercontent.com/37660499/71682046-852e7900-2db4-11ea-86bb-cea15364a04c.png)
but now the code in master branch of the repository has been changed
![image](https://user-images.githubusercontent.com/37660499/71682087-a1cab100-2db4-11ea-867e-87ad73149880.png)

pls look into it once or is there some error from my side

**Comment by Aastha12345** [comment]
earlier i think so it was working fine

**Comment by thebishaldeb** [comment]
Assigning it to you for correction
